UserContextValues's userRole in App now uses backend api to get user's role
HKN-UCSD/hkn-member-portal pull request #164
Opened 2020-09-15 06:17 UTC by thaigillespie

It used to get the roles from firebase custom claims.

2020-09-15 06:25 UTC, thaigillespie commented
Lmao since this needs the auth page refresh bug fix + legit test accounts the cypress literally cannot pass : (

2020-09-15 06:26 UTC, thaigillespie commented
Or well it needs the TODOs that I put in as comments at least. I left the TODOs there bc I thouht you'd have to do smth like that for the auth page refresh bug fix @godwinpang. Let me know if that is or isn't the case. If it isn't, I'll do the TODOs myself.

2020-09-15 18:43 UTC, godwinpang commented on src/pages/App/index.tsx
> +        const userRole = await getUserRole(id);
don't await on both here - make them promises and do a promise.all - i want both awaits to go out together

2020-09-15 18:47 UTC, godwinpang requested changes

2020-09-15 18:47 UTC, godwinpang commented on src/pages/App/index.tsx
> +        const userRole = await getUserRole(id);
don't await on both here - make them promises and do a promise.all - i want both awaits to go out together

2020-09-16 07:16 UTC, godwinpang approved these changes

2020-09-16 07:17 UTC, merged