Add CardWithVerticalTabs, with 3 tables to check off, view attendances, and view RSVPs
HKN-UCSD/hkn-member-portal pull request #211
Opened 2021-01-25 06:39 UTC by thaigillespie

Everything works, but the tables look kinda scuffed on the CardWithVerticalTabs component and I don't know how to fix that : (

Some images:

![Screenshot_2021-01-24 Member Portal Eta Kappa Nu Kappa Psi - HKN UCSD(2)](https://user-images.githubusercontent.com/42761684/105669878-f1cf5680-5e94-11eb-9fc1-7d6ae908664e.png)

![Screenshot_2021-01-24 Member Portal Eta Kappa Nu Kappa Psi - HKN UCSD(1)](https://user-images.githubusercontent.com/42761684/105669880-f1cf5680-5e94-11eb-9719-653e39a5508e.png)

![Screenshot_2021-01-24 Member Portal Eta Kappa Nu Kappa Psi - HKN UCSD](https://user-images.githubusercontent.com/42761684/105669881-f267ed00-5e94-11eb-9b6c-e9c25833d589.png)

2021-01-25 06:45 UTC, godwinpang requested changes

2021-01-25 06:45 UTC, godwinpang commented on src/pages/EventDetailsPage/components/AttendanceTable/index.tsx
> +  const attendanceData = attendances.map(attendance => {
this is a pretty big anon function, can we pull it out somewhere?

2021-01-25 06:46 UTC, godwinpang commented
looks good, can we do a demo at events meeting this tuesday at 5pm and see what they think?

2021-01-25 07:04 UTC, thaigillespie commented
@godwinpang yes a demo should be fine

2021-02-05 03:43 UTC, godwinpang requested changes

2021-02-13 23:52 UTC, godwinpang submitted a review, later dismissed

2021-02-14 00:34 UTC, merged